<?php
namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{

    public function getListByMark(string $mark)
    {
        $res = $this->findOneBy([
            'deviceMark' => $mark
        ]);
        
        return $res;
    }
}
