<?php
namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * 根据GroupID查询用户
     * 
     * @param string $name
     */
    public function getUserListByName(string $name)
    {
        $query = $this->createQueryBuilder('u')
            ->where("u.nameAlias =:name")
            ->orderBy('u.id', 'DESC')
            ->setParameter('name', $name)
            ->getQuery();
        $result = $query->getResult();
        return $result ? $result : new User();
    }
}
