# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    memcached.servers:
        - { host: 127.0.0.1, port: 11211 }

services:
    userservice:
        class: AppBundle\Service\UserService
    memcached:
        class: Memcached
        calls:
            - [ addServers, [ %memcached.servers% ]]