# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    memcached.servers:
        - { host: 127.0.0.1, port: 11211 }

services:
    # default configuration for services in *this* file
    signatureCheckService:
        class: AppBundle\EventSubscriber\SignatureSubscriber
        autowire: true
        autoconfigure: true
        public: false
        arguments:
            $privatekey: "%privatekey%"
    userservice:
        class: AppBundle\Service\UserService
    curlservice:
        class: AppBundle\Service\CurlService
    memcached:
        class: Memcached
        calls:
            - [ addServers, [ %memcached.servers% ]]